### PR TITLE
Add/new file title includes a unicode char ա

### PR DESCRIPTION
**Pull request by bugron**

### CODE REVIEW

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by BerkeleyFalse** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by BerkeleyFalse** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by BerkeleyFalse** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by BerkeleyFalse** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
@bugron thanks for the PR.
Your branch name should start with one of `fix/, feature/` prefixes. Name, your branches correctly next time, please.
Do not include issue numbers and following [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in commit messages.
You have pushed more than one commit. When you finish editing, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) your commits into one.
Please, review our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Pull request closed without merging**
